/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.AdminController;
import Controler.DonationController;
import Controler.OrganisasiController;
import Controler.ViewController;
import Model.PenggalanganDana;
import Model.User;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvan
 */
public class AdminEditDonate extends javax.swing.JFrame {
    private static boolean kon;
    private static int idpeng;
     private int id;
    private File selectedFile;
    private PenggalanganDana penggalangan;
    
    public AdminEditDonate(int id,boolean kon,int idpeng) {
        initComponents();
        this.idpeng=idpeng;
        this.kon=kon;
        this.id = id;
        OrganisasiController orgCtrl = new OrganisasiController();
        PenggalanganDana penggalangan = DonationController.getPenggalangByID(id);
        User user = orgCtrl.getById(penggalangan.getOrganisasiId());
        ImageIcon img = new ImageIcon(ViewController.blobToImage(penggalangan.getImage()));
        
        gmbr1.setIcon(img);
        judul1.setText(penggalangan.getJudul());
        organisasi1.setText(user.getUsername());
        uang1.setText(String.valueOf(DonationController.getTotalDonasiPenggalangan(penggalangan.getId())));
        donatur1.setText(String.valueOf(DonationController.getTotalDonatur(penggalangan.getId()))+" Donatur");
        
        String[] deskripsi = penggalangan.getDeskripsi().split("(?<=\\G.{100})");
        paragraf2.setVisible(false);
        paragraf3.setVisible(false);
        
        System.out.println(deskripsi.length);
        paragraf1.setText(deskripsi[0]);
        if (deskripsi.length==2){
            paragraf2.setVisible(true);
            paragraf2.setText(deskripsi[1]);    
        }
        if (deskripsi.length==3){
            paragraf2.setVisible(true);
            paragraf3.setVisible(true);
            paragraf2.setText(deskripsi[1]);  
            paragraf3.setText(deskripsi[2]);    
        }
        
        String[] lokasi = penggalangan.getLokasi().split("(?<=\\G.{100})");
        lokasi2.setVisible(false);
        lokasi3.setVisible(false);
        
        System.out.println(deskripsi.length);
        lokasi1.setText(lokasi[0]);
        if (lokasi.length==2){
            lokasi2.setVisible(true);
            lokasi2.setText(lokasi[1]);    
        }
        if (lokasi.length==3){
            lokasi2.setVisible(true);
            lokasi3.setVisible(true);
            lokasi2.setText(lokasi[1]);  
            lokasi3.setText(lokasi[2]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        donate = new javax.swing.JButton();
        progress1 = new javax.swing.JProgressBar();
        gmbr1 = new javax.swing.JLabel();
        paragraf3 = new javax.swing.JLabel();
        paragraf2 = new javax.swing.JLabel();
        paragraf1 = new javax.swing.JLabel();
        lokasi2 = new javax.swing.JLabel();
        lokasi3 = new javax.swing.JLabel();
        lokasi1 = new javax.swing.JLabel();
        organisasi1 = new javax.swing.JLabel();
        uang1 = new javax.swing.JLabel();
        donatur1 = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        donasi1 = new javax.swing.JPanel();
        LokasiFeild = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        Confrim = new javax.swing.JButton();
        JudulField = new javax.swing.JTextField();
        DetailFeild = new javax.swing.JTextField();
        Target = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        donate.setText("Donasi");
        donate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donateActionPerformed(evt);
            }
        });

        gmbr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IMG/346x130.png"))); // NOI18N

        paragraf3.setText("1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");

        paragraf2.setText("1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");

        paragraf1.setText("1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");

        lokasi2.setText("1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");

        lokasi3.setText("1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");

        lokasi1.setText("1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890");

        organisasi1.setText("Nama Organisasi");

        uang1.setText("Uang");

        donatur1.setText("Donatur");

        judul1.setText("Judul");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout donasi1Layout = new javax.swing.GroupLayout(donasi1);
        donasi1.setLayout(donasi1Layout);
        donasi1Layout.setHorizontalGroup(
            donasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(LokasiFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        donasi1Layout.setVerticalGroup(
            donasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donasi1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LokasiFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Detail");

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel2.setText("Lokasi");

        jLabel4.setText("Target");

        jLabel5.setText("Unggah");

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        Confrim.setText("Confrim");
        Confrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfrimActionPerformed(evt);
            }
        });

        JudulField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JudulFieldActionPerformed(evt);
            }
        });

        DetailFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailFeildActionPerformed(evt);
            }
        });

        Target.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TargetActionPerformed(evt);
            }
        });

        jLabel6.setText("judul");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(308, 308, 308)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Confrim)
                            .addComponent(donasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(171, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(DetailFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(Target, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(341, 341, 341))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)
                                .addComponent(JudulField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2)
                                .addGap(478, 478, 478))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JudulField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(DetailFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(donasi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Confrim)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Target, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
        new DonaturListDonate().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void donateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donateActionPerformed
      
    }//GEN-LAST:event_donateActionPerformed

    private void ConfrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfrimActionPerformed
 String newJudul = JudulField.getText();
    String newDetail = DetailFeild.getText();
    String newTargetStr = Target.getText();
    String newLokasi = LokasiFeild.getText();

    long newTarget;
    try {
        newTarget = Long.parseLong(newTargetStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Target must be a valid number");
        return;
    }

    if (newJudul.isEmpty() || newDetail.isEmpty() || newLokasi.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields");
        return;
    }

    try {
        // Load the image from the selected file
        InputStream imageStream = null;
        if (selectedFile != null) {
            imageStream = new FileInputStream(selectedFile);
        }

        // Create a new PenggalanganDana object with updated data
        
        System.out.println("yang ini ga");
        System.out.println(id);
        System.out.println(newJudul);
        System.out.println(newLokasi);
        System.out.println(kon);
        System.out.println(idpeng);
        //System.out.println(penggalangan.getOrganisasiId());
        System.out.println(imageStream);
        PenggalanganDana updatedPenggalangan = new PenggalanganDana(id, newJudul, newDetail, newLokasi, kon, idpeng, imageStream, (int) newTarget);
        System.out.println("ciaaa");
        // Call the controller to update the data
        boolean success = AdminController.editPenggalangan(updatedPenggalangan);
        if (success) {
            JOptionPane.showMessageDialog(this, "Penggalangan Dana updated successfully");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update Penggalangan Dana");
        }
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Failed to update Penggalangan Dana");
    }     
    }//GEN-LAST:event_ConfrimActionPerformed

    private void DetailFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DetailFeildActionPerformed

    private void TargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TargetActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        selectedFile = jFileChooser1.getSelectedFile();
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void JudulFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JudulFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JudulFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEditDonate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEditDonate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEditDonate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEditDonate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("kon di run");
                new AdminEditDonate(1,kon,idpeng).setVisible(true);
            //    System.out.println("kon");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confrim;
    private javax.swing.JTextField DetailFeild;
    private javax.swing.JTextField JudulField;
    private javax.swing.JTextField LokasiFeild;
    private javax.swing.JTextField Target;
    private javax.swing.JButton back;
    private javax.swing.JPanel donasi1;
    private javax.swing.JButton donate;
    private javax.swing.JLabel donatur1;
    private javax.swing.JLabel gmbr1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel lokasi1;
    private javax.swing.JLabel lokasi2;
    private javax.swing.JLabel lokasi3;
    private javax.swing.JLabel organisasi1;
    private javax.swing.JLabel paragraf1;
    private javax.swing.JLabel paragraf2;
    private javax.swing.JLabel paragraf3;
    private javax.swing.JProgressBar progress1;
    private javax.swing.JLabel uang1;
    // End of variables declaration//GEN-END:variables
}
