/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controler.AdminController;
import Controler.DonationController;
import Controler.OrganisasiController;
import Controler.ViewController;
import Model.PenggalanganDana;
import Model.User;
import Model.UserSession;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvan
 */
public class AdminListDonate extends javax.swing.JFrame {
    OrganisasiController orgCtrl = new OrganisasiController();
    public int id1;
    public boolean confirm1;
    public boolean confirm2;
     public boolean confirm3;
      public boolean confirm4;
    public int idpeng1;
    public int idpeng2;
    public int idpeng3;
    public int idpeng4;
    
    public int id2;
    public int id3;
    public int id4;

    public AdminListDonate() {
        initComponents();
        loadPenggalangan(1);
    }
    
    private void loadButton(int count){
        if (count/4 == 0 || count%4 >=0){
            page1.setVisible(true);
        } 
        if (count/4 > 1 || (count/4 == 1 && count%4 >0)){
            page2.setVisible(true);
        } 
        if (count/4 > 2 || (count/4 == 2 && count%4 >0)){
            page3.setVisible(true);
        } 
        if (count/4 > 3 || (count/4 == 3 && count%4 >0)){
            page4.setVisible(true);
        } 
        if (count/4 > 4 || (count/4 == 4 && count%4 >0)){
            page5.setVisible(true);
        } 
        if (count/4 > 5 || (count/4 == 5 && count%4 >0)){
            page6.setVisible(true);
        } 
        if (count/4 > 6 || (count/4 == 6 && count%4 >0)){
            page7.setVisible(true);
        } 
        if (count/4 > 7 ||(count/4 == 7 && count%4 >0)){
            page8.setVisible(true);
        } 
        if (count/4 > 8 || (count/4 == 8 && count%4 >0)){
            page9.setVisible(true);
        }
        if (count/4 > 9 || (count/4 == 9 && count%4 >0)){
            page10.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gmbr3 = new javax.swing.JLabel();
        donasi3 = new javax.swing.JPanel();
        judul3 = new javax.swing.JLabel();
        organisasi3 = new javax.swing.JLabel();
        progress3 = new javax.swing.JProgressBar();
        uang3 = new javax.swing.JLabel();
        donatur3 = new javax.swing.JLabel();
        gmbr4 = new javax.swing.JLabel();
        organisasi4 = new javax.swing.JLabel();
        donasi4 = new javax.swing.JPanel();
        judul4 = new javax.swing.JLabel();
        progress4 = new javax.swing.JProgressBar();
        uang4 = new javax.swing.JLabel();
        donatur4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        donasi5 = new javax.swing.JPanel();
        gmbr5 = new javax.swing.JLabel();
        judul5 = new javax.swing.JLabel();
        organisasi5 = new javax.swing.JLabel();
        progress5 = new javax.swing.JProgressBar();
        uang5 = new javax.swing.JLabel();
        donatur5 = new javax.swing.JLabel();
        Terima1 = new javax.swing.JButton();
        tolak2 = new javax.swing.JButton();
        edit2 = new javax.swing.JButton();
        donasi6 = new javax.swing.JPanel();
        gmbr6 = new javax.swing.JLabel();
        judul6 = new javax.swing.JLabel();
        organisasi6 = new javax.swing.JLabel();
        progress6 = new javax.swing.JProgressBar();
        uang6 = new javax.swing.JLabel();
        donatur6 = new javax.swing.JLabel();
        edit3 = new javax.swing.JButton();
        tolak3 = new javax.swing.JButton();
        Terima3 = new javax.swing.JButton();
        donatur7 = new javax.swing.JLabel();
        uang7 = new javax.swing.JLabel();
        gmbr7 = new javax.swing.JLabel();
        tolak4 = new javax.swing.JButton();
        edit4 = new javax.swing.JButton();
        judul7 = new javax.swing.JLabel();
        organisasi7 = new javax.swing.JLabel();
        progress7 = new javax.swing.JProgressBar();
        Terima4 = new javax.swing.JButton();
        donasi1 = new javax.swing.JPanel();
        gmbr1 = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        organisasi1 = new javax.swing.JLabel();
        progress1 = new javax.swing.JProgressBar();
        uang1 = new javax.swing.JLabel();
        donatur1 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        tolak1 = new javax.swing.JButton();
        Terima2 = new javax.swing.JButton();
        donasi2 = new javax.swing.JPanel();
        gmbr2 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        organisasi2 = new javax.swing.JLabel();
        progress2 = new javax.swing.JProgressBar();
        uang2 = new javax.swing.JLabel();
        donatur2 = new javax.swing.JLabel();
        Terima = new javax.swing.JButton();
        tolak = new javax.swing.JButton();
        edit1 = new javax.swing.JButton();
        donasi7 = new javax.swing.JPanel();
        gmbr8 = new javax.swing.JLabel();
        judul8 = new javax.swing.JLabel();
        organisasi8 = new javax.swing.JLabel();
        progress8 = new javax.swing.JProgressBar();
        uang8 = new javax.swing.JLabel();
        donatur8 = new javax.swing.JLabel();
        Terima5 = new javax.swing.JButton();
        tolak5 = new javax.swing.JButton();
        edit5 = new javax.swing.JButton();
        donasi8 = new javax.swing.JPanel();
        gmbr9 = new javax.swing.JLabel();
        judul9 = new javax.swing.JLabel();
        organisasi9 = new javax.swing.JLabel();
        progress9 = new javax.swing.JProgressBar();
        uang9 = new javax.swing.JLabel();
        donatur9 = new javax.swing.JLabel();
        Terima6 = new javax.swing.JButton();
        tolak6 = new javax.swing.JButton();
        edit6 = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        page2 = new javax.swing.JButton();
        page1 = new javax.swing.JButton();
        page3 = new javax.swing.JButton();
        page4 = new javax.swing.JButton();
        page5 = new javax.swing.JButton();
        page6 = new javax.swing.JButton();
        page7 = new javax.swing.JButton();
        page10 = new javax.swing.JButton();
        page9 = new javax.swing.JButton();
        page8 = new javax.swing.JButton();

        gmbr3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IMG/346x130.png"))); // NOI18N

        judul3.setText("Judul");

        organisasi3.setText("Nama Organisasi");

        uang3.setText("Uang");

        donatur3.setText("Donatur");

        javax.swing.GroupLayout donasi3Layout = new javax.swing.GroupLayout(donasi3);
        donasi3.setLayout(donasi3Layout);
        donasi3Layout.setHorizontalGroup(
            donasi3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(donasi3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donasi3Layout.createSequentialGroup()
                        .addGroup(donasi3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progress3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(donasi3Layout.createSequentialGroup()
                                .addGroup(donasi3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(judul3)
                                    .addComponent(organisasi3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(donasi3Layout.createSequentialGroup()
                        .addComponent(uang3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(donatur3)
                        .addGap(33, 33, 33))))
        );
        donasi3Layout.setVerticalGroup(
            donasi3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi3Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(judul3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(organisasi3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donasi3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uang3)
                    .addComponent(donatur3))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        gmbr4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IMG/346x130.png"))); // NOI18N

        organisasi4.setText("Nama Organisasi");

        judul4.setText("Judul");

        uang4.setText("Uang");

        donatur4.setText("Donatur");

        javax.swing.GroupLayout donasi4Layout = new javax.swing.GroupLayout(donasi4);
        donasi4.setLayout(donasi4Layout);
        donasi4Layout.setHorizontalGroup(
            donasi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(donasi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donasi4Layout.createSequentialGroup()
                        .addGroup(donasi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progress4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(donasi4Layout.createSequentialGroup()
                                .addComponent(judul4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(donasi4Layout.createSequentialGroup()
                        .addComponent(uang4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(donatur4)
                        .addGap(33, 33, 33))))
        );
        donasi4Layout.setVerticalGroup(
            donasi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi4Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(judul4)
                .addGap(26, 26, 26)
                .addComponent(progress4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donasi4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uang4)
                    .addComponent(donatur4))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        donasi5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donasi5MouseClicked(evt);
            }
        });

        gmbr5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IMG/346x130.png"))); // NOI18N

        judul5.setText("Judul");

        organisasi5.setText("Nama Organisasi");

        uang5.setText("Uang");

        donatur5.setText("Donatur");

        Terima1.setText("Terima");
        Terima1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Terima1ActionPerformed(evt);
            }
        });

        tolak2.setText("tolak");
        tolak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolak2ActionPerformed(evt);
            }
        });

        edit2.setText("edit");
        edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donasi5Layout = new javax.swing.GroupLayout(donasi5);
        donasi5.setLayout(donasi5Layout);
        donasi5Layout.setHorizontalGroup(
            donasi5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gmbr5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(donasi5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(donasi5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donasi5Layout.createSequentialGroup()
                        .addComponent(judul5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(donasi5Layout.createSequentialGroup()
                        .addGroup(donasi5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progress5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(donasi5Layout.createSequentialGroup()
                                .addComponent(organisasi5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edit2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Terima1)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tolak2)
                        .addGap(12, 12, 12))
                    .addGroup(donasi5Layout.createSequentialGroup()
                        .addComponent(uang5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(donatur5)
                        .addGap(33, 33, 33))))
        );
        donasi5Layout.setVerticalGroup(
            donasi5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi5Layout.createSequentialGroup()
                .addComponent(gmbr5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donasi5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organisasi5)
                    .addComponent(edit2)
                    .addComponent(Terima1)
                    .addComponent(tolak2))
                .addGap(18, 18, 18)
                .addComponent(progress5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donasi5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uang5)
                    .addComponent(donatur5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        donasi6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donasi6MouseClicked(evt);
            }
        });

        gmbr6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IMG/346x130.png"))); // NOI18N

        judul6.setText("Judul");

        organisasi6.setText("Nama Organisasi");

        uang6.setText("Uang");

        donatur6.setText("Donatur");

        edit3.setText("edit");
        edit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit3ActionPerformed(evt);
            }
        });

        tolak3.setText("tolak");
        tolak3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolak3ActionPerformed(evt);
            }
        });

        Terima3.setText("Terima");
        Terima3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Terima3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donasi6Layout = new javax.swing.GroupLayout(donasi6);
        donasi6.setLayout(donasi6Layout);
        donasi6Layout.setHorizontalGroup(
            donasi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi6Layout.createSequentialGroup()
                .addComponent(gmbr6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(donasi6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(donasi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donasi6Layout.createSequentialGroup()
                        .addGroup(donasi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judul6)
                            .addComponent(progress6, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(donasi6Layout.createSequentialGroup()
                                .addComponent(uang6)
                                .addGap(227, 227, 227)
                                .addComponent(donatur6)))
                        .addContainerGap())
                    .addGroup(donasi6Layout.createSequentialGroup()
                        .addComponent(organisasi6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Terima3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tolak3))))
        );
        donasi6Layout.setVerticalGroup(
            donasi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi6Layout.createSequentialGroup()
                .addComponent(gmbr6)
                .addGap(7, 7, 7)
                .addComponent(judul6)
                .addGap(3, 3, 3)
                .addGroup(donasi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organisasi6)
                    .addComponent(edit3)
                    .addComponent(tolak3)
                    .addComponent(Terima3))
                .addGap(18, 18, 18)
                .addComponent(progress6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(donasi6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uang6)
                    .addComponent(donatur6)))
        );

        donatur7.setText("Donatur");

        uang7.setText("Uang");

        gmbr7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IMG/346x130.png"))); // NOI18N

        tolak4.setText("tolak");
        tolak4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolak4ActionPerformed(evt);
            }
        });

        edit4.setText("edit");
        edit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit4ActionPerformed(evt);
            }
        });

        judul7.setText("Judul");

        organisasi7.setText("Nama Organisasi");

        Terima4.setText("Terima");
        Terima4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Terima4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gmbr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IMG/346x130.png"))); // NOI18N

        judul1.setText("Judul");

        organisasi1.setText("Nama Organisasi");

        uang1.setText("Uang");

        donatur1.setText("Donatur");

        edit.setText("edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        tolak1.setText("tolak");
        tolak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolak1ActionPerformed(evt);
            }
        });

        Terima2.setText("Terima");
        Terima2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Terima2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donasi1Layout = new javax.swing.GroupLayout(donasi1);
        donasi1.setLayout(donasi1Layout);
        donasi1Layout.setHorizontalGroup(
            donasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi1Layout.createSequentialGroup()
                .addComponent(gmbr1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(donasi1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(donasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donasi1Layout.createSequentialGroup()
                        .addGroup(donasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(judul1)
                            .addComponent(progress1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(donasi1Layout.createSequentialGroup()
                                .addComponent(uang1)
                                .addGap(227, 227, 227)
                                .addComponent(donatur1)))
                        .addContainerGap())
                    .addGroup(donasi1Layout.createSequentialGroup()
                        .addComponent(organisasi1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Terima2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tolak1))))
        );
        donasi1Layout.setVerticalGroup(
            donasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi1Layout.createSequentialGroup()
                .addComponent(gmbr1)
                .addGap(7, 7, 7)
                .addComponent(judul1)
                .addGap(3, 3, 3)
                .addGroup(donasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organisasi1)
                    .addComponent(edit)
                    .addComponent(tolak1)
                    .addComponent(Terima2))
                .addGap(18, 18, 18)
                .addComponent(progress1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(donasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uang1)
                    .addComponent(donatur1)))
        );

        getContentPane().add(donasi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 13, -1, 199));

        gmbr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IMG/346x130.png"))); // NOI18N

        judul2.setText("Judul");

        organisasi2.setText("Nama Organisasi");

        uang2.setText("Uang");

        donatur2.setText("Donatur");

        Terima.setText("Terima");
        Terima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerimaActionPerformed(evt);
            }
        });

        tolak.setText("tolak");
        tolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolakActionPerformed(evt);
            }
        });

        edit1.setText("edit");
        edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donasi2Layout = new javax.swing.GroupLayout(donasi2);
        donasi2.setLayout(donasi2Layout);
        donasi2Layout.setHorizontalGroup(
            donasi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gmbr2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
            .addGroup(donasi2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(donasi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donasi2Layout.createSequentialGroup()
                        .addComponent(judul2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(donasi2Layout.createSequentialGroup()
                        .addGroup(donasi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progress2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(donasi2Layout.createSequentialGroup()
                                .addComponent(organisasi2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edit1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Terima)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tolak)
                        .addGap(12, 12, 12))
                    .addGroup(donasi2Layout.createSequentialGroup()
                        .addComponent(uang2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(donatur2)
                        .addGap(33, 33, 33))))
        );
        donasi2Layout.setVerticalGroup(
            donasi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi2Layout.createSequentialGroup()
                .addComponent(gmbr2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donasi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organisasi2)
                    .addComponent(edit1)
                    .addComponent(Terima)
                    .addComponent(tolak))
                .addGap(18, 18, 18)
                .addComponent(progress2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donasi2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uang2)
                    .addComponent(donatur2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(donasi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 13, -1, 199));

        gmbr8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IMG/346x130.png"))); // NOI18N

        judul8.setText("Judul");

        organisasi8.setText("Nama Organisasi");

        uang8.setText("Uang");

        donatur8.setText("Donatur");

        Terima5.setText("Terima");
        Terima5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Terima5ActionPerformed(evt);
            }
        });

        tolak5.setText("tolak");
        tolak5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolak5ActionPerformed(evt);
            }
        });

        edit5.setText("edit");
        edit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donasi7Layout = new javax.swing.GroupLayout(donasi7);
        donasi7.setLayout(donasi7Layout);
        donasi7Layout.setHorizontalGroup(
            donasi7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gmbr8, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
            .addGroup(donasi7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(donasi7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donasi7Layout.createSequentialGroup()
                        .addComponent(judul8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(donasi7Layout.createSequentialGroup()
                        .addGroup(donasi7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progress8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(donasi7Layout.createSequentialGroup()
                                .addComponent(organisasi8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edit5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Terima5)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tolak5)
                        .addGap(12, 12, 12))
                    .addGroup(donasi7Layout.createSequentialGroup()
                        .addComponent(uang8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(donatur8)
                        .addGap(33, 33, 33))))
        );
        donasi7Layout.setVerticalGroup(
            donasi7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi7Layout.createSequentialGroup()
                .addComponent(gmbr8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donasi7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organisasi8)
                    .addComponent(edit5)
                    .addComponent(Terima5)
                    .addComponent(tolak5))
                .addGap(18, 18, 18)
                .addComponent(progress8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donasi7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uang8)
                    .addComponent(donatur8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(donasi7, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 230, -1, 199));

        gmbr9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IMG/346x130.png"))); // NOI18N

        judul9.setText("Judul");

        organisasi9.setText("Nama Organisasi");

        uang9.setText("Uang");

        donatur9.setText("Donatur");

        Terima6.setText("Terima");
        Terima6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Terima6ActionPerformed(evt);
            }
        });

        tolak6.setText("tolak");
        tolak6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tolak6ActionPerformed(evt);
            }
        });

        edit6.setText("edit");
        edit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donasi8Layout = new javax.swing.GroupLayout(donasi8);
        donasi8.setLayout(donasi8Layout);
        donasi8Layout.setHorizontalGroup(
            donasi8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gmbr9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(donasi8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(donasi8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donasi8Layout.createSequentialGroup()
                        .addComponent(judul9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(donasi8Layout.createSequentialGroup()
                        .addGroup(donasi8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progress9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(donasi8Layout.createSequentialGroup()
                                .addComponent(organisasi9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edit6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Terima6)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tolak6)
                        .addGap(12, 12, 12))
                    .addGroup(donasi8Layout.createSequentialGroup()
                        .addComponent(uang9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(donatur9)
                        .addGap(33, 33, 33))))
        );
        donasi8Layout.setVerticalGroup(
            donasi8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donasi8Layout.createSequentialGroup()
                .addComponent(gmbr9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judul9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donasi8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organisasi9)
                    .addComponent(edit6)
                    .addComponent(Terima6)
                    .addComponent(tolak6))
                .addGap(18, 18, 18)
                .addComponent(progress9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(donasi8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uang9)
                    .addComponent(donatur9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(donasi8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 199));

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, -1, -1));

        page2.setText("2");
        page2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page2ActionPerformed(evt);
            }
        });
        getContentPane().add(page2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 436, -1, -1));

        page1.setText("1");
        page1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page1ActionPerformed(evt);
            }
        });
        getContentPane().add(page1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 436, -1, -1));

        page3.setText("3");
        page3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page3ActionPerformed(evt);
            }
        });
        getContentPane().add(page3, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 436, -1, -1));

        page4.setText("4");
        page4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page4ActionPerformed(evt);
            }
        });
        getContentPane().add(page4, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 436, -1, -1));

        page5.setText("5");
        page5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page5ActionPerformed(evt);
            }
        });
        getContentPane().add(page5, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 436, -1, -1));

        page6.setText("6");
        page6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page6ActionPerformed(evt);
            }
        });
        getContentPane().add(page6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 436, -1, -1));

        page7.setText("7");
        page7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page7ActionPerformed(evt);
            }
        });
        getContentPane().add(page7, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 436, -1, -1));

        page10.setText("10");
        page10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page10ActionPerformed(evt);
            }
        });
        getContentPane().add(page10, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 436, -1, -1));

        page9.setText("9");
        page9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page9ActionPerformed(evt);
            }
        });
        getContentPane().add(page9, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 436, -1, -1));

        page8.setText("8");
        page8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page8ActionPerformed(evt);
            }
        });
        getContentPane().add(page8, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 436, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolakActionPerformed
         // Mendapatkan ID penggalangan yang diklik
    // Mendapatkan ID penggalangan yang diklik
    int clickedPenggalanganId = id2;
    
    // Memanggil metode unconfirmPenggalangan dari DonationController untuk menolak penggalangan dana
    boolean result = AdminController.delete(clickedPenggalanganId);
    
    // Menampilkan pesan berhasil atau gagal
    if (result) {
        JOptionPane.showMessageDialog(this, "Penggalangan dana telah ditolak.");
            loadPenggalangan(1);
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menolak penggalangan dana.");
    }
    }//GEN-LAST:event_tolakActionPerformed

    private void TerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerimaActionPerformed
          int clickedPenggalanganId = id2;
    
    // Memanggil metode unconfirmPenggalangan dari DonationController untuk menolak penggalangan dana
    boolean result = AdminController.Terima(clickedPenggalanganId);
    
    // Menampilkan pesan berhasil atau gagal
    if (result) {
        JOptionPane.showMessageDialog(this, "Penggalangan berhasil di terima.");
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menerima .");
    }
    }//GEN-LAST:event_TerimaActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
         new AdminEditDonate(id1,confirm1,idpeng1).setVisible(true);
           this.dispose();
    }//GEN-LAST:event_editActionPerformed

    private void tolak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolak1ActionPerformed
        int clickedPenggalanganId = id1;
    
    // Memanggil metode unconfirmPenggalangan dari DonationController untuk menolak penggalangan dana
    boolean result = AdminController.delete(clickedPenggalanganId);
    
    // Menampilkan pesan berhasil atau gagal
    if (result) {
        JOptionPane.showMessageDialog(this, "Penggalangan dana telah ditolak.");
            loadPenggalangan(1);
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menolak penggalangan dana.");
    }
    }//GEN-LAST:event_tolak1ActionPerformed

    private void Terima2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Terima2ActionPerformed
        int clickedPenggalanganId =id1;
    
    // Memanggil metode unconfirmPenggalangan dari DonationController untuk menolak penggalangan dana
    boolean result = AdminController.Terima(clickedPenggalanganId);
    
    // Menampilkan pesan berhasil atau gagal
    if (result) {
        JOptionPane.showMessageDialog(this, "Penggalangan berhasil di terima.");
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menerima .");
    }
    }//GEN-LAST:event_Terima2ActionPerformed

    private void edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1ActionPerformed
         new AdminEditDonate(id2,confirm2,idpeng2).setVisible(true);
           this.dispose();
    }//GEN-LAST:event_edit1ActionPerformed

    private void Terima1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Terima1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Terima1ActionPerformed

    private void tolak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolak2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tolak2ActionPerformed

    private void edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit2ActionPerformed

    private void donasi5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donasi5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_donasi5MouseClicked

    private void edit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit3ActionPerformed

    private void tolak3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolak3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tolak3ActionPerformed

    private void Terima3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Terima3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Terima3ActionPerformed

    private void donasi6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donasi6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_donasi6MouseClicked

    private void tolak4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolak4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tolak4ActionPerformed

    private void edit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit4ActionPerformed

    private void Terima4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Terima4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Terima4ActionPerformed

    private void Terima5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Terima5ActionPerformed
        // TODO add your handling code here:
                int clickedPenggalanganId = id4;
    
    // Memanggil metode unconfirmPenggalangan dari DonationController untuk menolak penggalangan dana
    boolean result = AdminController.Terima(clickedPenggalanganId);
    
    // Menampilkan pesan berhasil atau gagal
    if (result) {
        JOptionPane.showMessageDialog(this, "Penggalangan berhasil di terima.");
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menerima.");
    }
                                        

    }//GEN-LAST:event_Terima5ActionPerformed

    private void tolak5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolak5ActionPerformed
                int clickedPenggalanganId = id4;
    
    // Memanggil metode unconfirmPenggalangan dari DonationController untuk menolak penggalangan dana
    boolean result = AdminController.delete(clickedPenggalanganId);
    
    // Menampilkan pesan berhasil atau gagal
    if (result) {
        JOptionPane.showMessageDialog(this, "Penggalangan dana telah ditolak.");
            loadPenggalangan(1);
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menolak penggalangan dana.");
    }
                                         

    }//GEN-LAST:event_tolak5ActionPerformed

    private void edit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit5ActionPerformed

         new AdminEditDonate(id4,confirm4,idpeng4).setVisible(true);
           this.dispose();
    }//GEN-LAST:event_edit5ActionPerformed

    private void Terima6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Terima6ActionPerformed
         int clickedPenggalanganId =id3;
    
    // Memanggil metode unconfirmPenggalangan dari DonationController untuk menolak penggalangan dana
    boolean result = AdminController.Terima(clickedPenggalanganId);
    
    // Menampilkan pesan berhasil atau gagal
    if (result) {
        JOptionPane.showMessageDialog(this, "Penggalangan berhasil di terima.");
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menerima .");
    }
    }//GEN-LAST:event_Terima6ActionPerformed

    private void tolak6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tolak6ActionPerformed
                int clickedPenggalanganId = id3;
    
    // Memanggil metode unconfirmPenggalangan dari DonationController untuk menolak penggalangan dana
    boolean result = AdminController.delete(clickedPenggalanganId);
        loadPenggalangan(1);
    
    // Menampilkan pesan berhasil atau gagal
    if (result) {
        JOptionPane.showMessageDialog(this, "Penggalangan dana telah ditolak.");
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menolak penggalangan dana.");
    }
    }//GEN-LAST:event_tolak6ActionPerformed

    private void edit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit6ActionPerformed
        // TODO add your handling code here:
         new AdminEditDonate(id3,confirm3,idpeng3).setVisible(true);
           this.dispose();
    }//GEN-LAST:event_edit6ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LogIn().setVisible(true);
        UserSession.clearSession();
    }//GEN-LAST:event_logoutActionPerformed

    private void page2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page2ActionPerformed
        loadPenggalangan(2);
    }//GEN-LAST:event_page2ActionPerformed

    private void page1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page1ActionPerformed
        loadPenggalangan(1);
    }//GEN-LAST:event_page1ActionPerformed

    private void page3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page3ActionPerformed
        loadPenggalangan(3);
    }//GEN-LAST:event_page3ActionPerformed

    private void page4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page4ActionPerformed
        loadPenggalangan(4);
    }//GEN-LAST:event_page4ActionPerformed

    private void page5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page5ActionPerformed
        loadPenggalangan(5);
    }//GEN-LAST:event_page5ActionPerformed

    private void page6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page6ActionPerformed
        loadPenggalangan(6);
    }//GEN-LAST:event_page6ActionPerformed

    private void page7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page7ActionPerformed
        loadPenggalangan(7);
    }//GEN-LAST:event_page7ActionPerformed

    private void page10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page10ActionPerformed
        loadPenggalangan(10);
    }//GEN-LAST:event_page10ActionPerformed

    private void page9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page9ActionPerformed
        loadPenggalangan(9);
    }//GEN-LAST:event_page9ActionPerformed

    private void page8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page8ActionPerformed
        loadPenggalangan(8);
    }//GEN-LAST:event_page8ActionPerformed

    private void loadPenggalangan(int page){
       donasi1.setVisible(false);
        donasi2.setVisible(false);
        donasi8.setVisible(false);
        donasi7.setVisible(false);
        page1.setVisible(false);
        page2.setVisible(false);
        page3.setVisible(false);
        page4.setVisible(false);
        page5.setVisible(false);
        page6.setVisible(false);
        page7.setVisible(false);
        page8.setVisible(false);
        page9.setVisible(false);
        page10.setVisible(false);
        
        List<PenggalanganDana> penggalanganList = DonationController.getAllPenggalangan();
        
        // hapus yg blom confirm
     
        
        loadButton(penggalanganList.size());
        int startIdx = (page - 1) * 4;
        
        int idx = 0;
        int count = 0;
        if (startIdx <= penggalanganList.size()) {
            loadCard1(penggalanganList.get(startIdx));
            id1 = penggalanganList.get(startIdx).getId();
            confirm1 = penggalanganList.get(startIdx).getConfirm();
            idpeng1=penggalanganList.get(startIdx).getOrganisasiId();
          
           
           
            donasi1.setVisible(true);
        }
        if (startIdx + 1 < penggalanganList.size()) {
            loadCard2(penggalanganList.get(startIdx + 1));
            id2 = penggalanganList.get(startIdx+1).getId();
            donasi2.setVisible(true);
               idpeng2=penggalanganList.get(startIdx+1).getOrganisasiId();
        }
        if (startIdx + 2 < penggalanganList.size()) {
            loadCard3(penggalanganList.get(startIdx + 2));
            id3 = penggalanganList.get(startIdx+2).getId();
               idpeng3=penggalanganList.get(startIdx+2).getOrganisasiId();
            donasi7.setVisible(true);
        }
        if (startIdx + 3 < penggalanganList.size()) {
            loadCard4(penggalanganList.get(startIdx + 3));
            id4 = penggalanganList.get(startIdx+3).getId();
               idpeng4=penggalanganList.get(startIdx+3).getOrganisasiId();
            donasi8.setVisible(true);
        }
    }
    
    private void loadCard1(PenggalanganDana obj){
        User user = orgCtrl.getById(obj.getOrganisasiId());
        ImageIcon img = new ImageIcon(ViewController.blobToImage(obj.getImage()));
        gmbr1.setIcon(img);
        judul1.setText(obj.getJudul());
        organisasi1.setText(user.getUsername());
        uang1.setText(String.valueOf(DonationController.getTotalDonasiPenggalangan(obj.getId())));
        donatur1.setText(String.valueOf(DonationController.getTotalDonatur(obj.getId()))+" Donatur");
    }
    
    private void loadCard2(PenggalanganDana obj){
        User user = orgCtrl.getById(obj.getOrganisasiId());
        ImageIcon img = new ImageIcon(ViewController.blobToImage(obj.getImage()));
        gmbr2.setIcon(img);
        judul2.setText(obj.getJudul());
        organisasi2.setText(user.getUsername());
        uang2.setText(String.valueOf(DonationController.getTotalDonasiPenggalangan(obj.getId())));
        donatur2.setText(String.valueOf(DonationController.getTotalDonatur(obj.getId()))+" Donatur");
    }
    
    private void loadCard3(PenggalanganDana obj){
        User user = orgCtrl.getById(obj.getOrganisasiId());
        ImageIcon img = new ImageIcon(ViewController.blobToImage(obj.getImage()));
        gmbr9.setIcon(img);
        judul9.setText(obj.getJudul());
        organisasi9.setText(user.getUsername());
        uang9.setText(String.valueOf(DonationController.getTotalDonasiPenggalangan(obj.getId())));
        donatur9.setText(String.valueOf(DonationController.getTotalDonatur(obj.getId()))+" Donatur");
    }
    
    private void loadCard4(PenggalanganDana obj){
        User user = orgCtrl.getById(obj.getOrganisasiId());
        ImageIcon img = new ImageIcon(ViewController.blobToImage(obj.getImage()));
        gmbr8.setIcon(img);
        judul8.setText(obj.getJudul());
        organisasi8.setText(user.getUsername());
        uang8.setText(String.valueOf(DonationController.getTotalDonasiPenggalangan(obj.getId())));
        donatur8.setText(String.valueOf(DonationController.getTotalDonatur(obj.getId()))+" Donatur");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminListDonate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminListDonate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminListDonate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminListDonate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminListDonate().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Terima;
    private javax.swing.JButton Terima1;
    private javax.swing.JButton Terima2;
    private javax.swing.JButton Terima3;
    private javax.swing.JButton Terima4;
    private javax.swing.JButton Terima5;
    private javax.swing.JButton Terima6;
    private javax.swing.JPanel donasi1;
    private javax.swing.JPanel donasi2;
    private javax.swing.JPanel donasi3;
    private javax.swing.JPanel donasi4;
    private javax.swing.JPanel donasi5;
    private javax.swing.JPanel donasi6;
    private javax.swing.JPanel donasi7;
    private javax.swing.JPanel donasi8;
    private javax.swing.JLabel donatur1;
    private javax.swing.JLabel donatur2;
    private javax.swing.JLabel donatur3;
    private javax.swing.JLabel donatur4;
    private javax.swing.JLabel donatur5;
    private javax.swing.JLabel donatur6;
    private javax.swing.JLabel donatur7;
    private javax.swing.JLabel donatur8;
    private javax.swing.JLabel donatur9;
    private javax.swing.JButton edit;
    private javax.swing.JButton edit1;
    private javax.swing.JButton edit2;
    private javax.swing.JButton edit3;
    private javax.swing.JButton edit4;
    private javax.swing.JButton edit5;
    private javax.swing.JButton edit6;
    private javax.swing.JLabel gmbr1;
    private javax.swing.JLabel gmbr2;
    private javax.swing.JLabel gmbr3;
    private javax.swing.JLabel gmbr4;
    private javax.swing.JLabel gmbr5;
    private javax.swing.JLabel gmbr6;
    private javax.swing.JLabel gmbr7;
    private javax.swing.JLabel gmbr8;
    private javax.swing.JLabel gmbr9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel judul4;
    private javax.swing.JLabel judul5;
    private javax.swing.JLabel judul6;
    private javax.swing.JLabel judul7;
    private javax.swing.JLabel judul8;
    private javax.swing.JLabel judul9;
    private javax.swing.JButton logout;
    private javax.swing.JLabel organisasi1;
    private javax.swing.JLabel organisasi2;
    private javax.swing.JLabel organisasi3;
    private javax.swing.JLabel organisasi4;
    private javax.swing.JLabel organisasi5;
    private javax.swing.JLabel organisasi6;
    private javax.swing.JLabel organisasi7;
    private javax.swing.JLabel organisasi8;
    private javax.swing.JLabel organisasi9;
    private javax.swing.JButton page1;
    private javax.swing.JButton page10;
    private javax.swing.JButton page2;
    private javax.swing.JButton page3;
    private javax.swing.JButton page4;
    private javax.swing.JButton page5;
    private javax.swing.JButton page6;
    private javax.swing.JButton page7;
    private javax.swing.JButton page8;
    private javax.swing.JButton page9;
    private javax.swing.JProgressBar progress1;
    private javax.swing.JProgressBar progress2;
    private javax.swing.JProgressBar progress3;
    private javax.swing.JProgressBar progress4;
    private javax.swing.JProgressBar progress5;
    private javax.swing.JProgressBar progress6;
    private javax.swing.JProgressBar progress7;
    private javax.swing.JProgressBar progress8;
    private javax.swing.JProgressBar progress9;
    private javax.swing.JButton tolak;
    private javax.swing.JButton tolak1;
    private javax.swing.JButton tolak2;
    private javax.swing.JButton tolak3;
    private javax.swing.JButton tolak4;
    private javax.swing.JButton tolak5;
    private javax.swing.JButton tolak6;
    private javax.swing.JLabel uang1;
    private javax.swing.JLabel uang2;
    private javax.swing.JLabel uang3;
    private javax.swing.JLabel uang4;
    private javax.swing.JLabel uang5;
    private javax.swing.JLabel uang6;
    private javax.swing.JLabel uang7;
    private javax.swing.JLabel uang8;
    private javax.swing.JLabel uang9;
    // End of variables declaration//GEN-END:variables
}
