/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Controler.DonationController.addDonasi;
import Model.Donasi;
import Model.UserSession;
import javax.swing.JOptionPane;

/**
 *
 * @author fiona
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    private int id;
    public Payment(int id) {
        initComponents();
        this.id = id;
        instantLAbel.setVisible(false);
        instantComboBox.setVisible(false);
        virtualComboBox.setVisible(false);
        virtualLabel.setVisible(false);
        transferLabel.setVisible(false);
        transferComboBox.setVisible(false);
    }

    private String getMetodePembayaran(){
       if(transferBank.isSelected()){ 
           return (String) transferComboBox.getSelectedItem();
       } else if(virtualAccount.isSelected()){
           return (String) virtualComboBox.getSelectedItem();
       } else if (instantPayment.isSelected()){
           return (String) instantComboBox.getSelectedItem();
       }
       return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        back = new javax.swing.JLabel();
        nominalInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        instantComboBox = new javax.swing.JComboBox<>();
        virtualComboBox = new javax.swing.JComboBox<>();
        instantLAbel = new javax.swing.JLabel();
        virtualLabel = new javax.swing.JLabel();
        transferLabel = new javax.swing.JLabel();
        transferComboBox = new javax.swing.JComboBox<>();
        instantPayment = new javax.swing.JRadioButton();
        virtualAccount = new javax.swing.JRadioButton();
        transferBank = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pesanInput = new javax.swing.JTextField();
        showName = new javax.swing.JRadioButton();
        confirmButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IMG/IconBack.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        jLabel1.setText("Rp, ");

        jLabel3.setText("Nominal Donasi");

        jLabel4.setText("Metode Pembayaran");

        instantComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qris", "Go Pay", "Dana", "ShopeePay" }));

        virtualComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCA Virtual Account", "BNI Virtual Account", "Mandiri Virtual Account", "BRI Virtual Account" }));

        instantLAbel.setText("Instant Payment");

        virtualLabel.setText("Virtual Account");

        transferLabel.setText("Transfer Bank");

        transferComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCA", "BNI", "Mandiri", "BRI" }));

        buttonGroup1.add(instantPayment);
        instantPayment.setText("Instant Payment");
        instantPayment.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                instantPaymentStateChanged(evt);
            }
        });

        buttonGroup1.add(virtualAccount);
        virtualAccount.setText("Virtual Account");
        virtualAccount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                virtualAccountStateChanged(evt);
            }
        });

        buttonGroup1.add(transferBank);
        transferBank.setText("Transfer Bank");
        transferBank.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                transferBankStateChanged(evt);
            }
        });

        jLabel8.setText("Personal Info");

        jLabel10.setText("Pesan");

        showName.setText("Show Your Name");

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Donate Now");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(nominalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(instantPayment)
                            .addComponent(virtualAccount)
                            .addComponent(transferBank)
                            .addComponent(instantLAbel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(instantComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(virtualComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(virtualLabel)
                            .addComponent(transferLabel)
                            .addComponent(transferComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(pesanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(confirmButton)))
                    .addComponent(jLabel11))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nominalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(pesanInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(showName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instantPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(virtualAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferBank)
                .addGap(18, 18, 18)
                .addComponent(instantLAbel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instantComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(virtualLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(virtualComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmButton))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        setVisible(false);
        new DetailDonate(id).setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void instantPaymentStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_instantPaymentStateChanged

        if (instantPayment.isSelected()){
            instantLAbel.setVisible(true);
            instantComboBox.setVisible(true);
            virtualComboBox.setVisible(false);
            virtualLabel.setVisible(false);
            transferLabel.setVisible(false);
            transferComboBox.setVisible(false);
        } 
        
    }//GEN-LAST:event_instantPaymentStateChanged

    private void virtualAccountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_virtualAccountStateChanged

         if (virtualAccount.isSelected()){
            instantLAbel.setVisible(false);
            instantComboBox.setVisible(false);
            virtualComboBox.setVisible(true);
            virtualLabel.setVisible(true);
            transferLabel.setVisible(false);
            transferComboBox.setVisible(false);
        } 
    }//GEN-LAST:event_virtualAccountStateChanged

    private void transferBankStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_transferBankStateChanged
         if (transferBank.isSelected()){
            instantLAbel.setVisible(false);
            instantComboBox.setVisible(false);
            virtualComboBox.setVisible(false);
            virtualLabel.setVisible(false);
            transferLabel.setVisible(true);
            transferComboBox.setVisible(true);
        } 
    }//GEN-LAST:event_transferBankStateChanged

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        int nominal = Integer.parseInt(nominalInput.getText());
        String pesan = pesanInput.getText();
        int idUser = UserSession.getId();
        int idPenggalangan = id;
        String metodePembayaran = getMetodePembayaran();
        String nama = "Hamba Allah 30 Tahu Spontan";
        if(showName.isSelected()){
            nama = UserSession.getUsername();
        }
        Donasi donasi = new Donasi(idUser, idPenggalangan, nominal, pesan, metodePembayaran, nama);
        System.out.println(metodePembayaran);
        System.out.println(id);
        addDonasi(donasi);
        JOptionPane.showMessageDialog(this, "Transaksi Berhasil!!??", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);
        setVisible(false);
        new ListDonate().setVisible(true);
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton confirmButton;
    private javax.swing.JComboBox<String> instantComboBox;
    private javax.swing.JLabel instantLAbel;
    private javax.swing.JRadioButton instantPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nominalInput;
    private javax.swing.JTextField pesanInput;
    private javax.swing.JRadioButton showName;
    private javax.swing.JRadioButton transferBank;
    private javax.swing.JComboBox<String> transferComboBox;
    private javax.swing.JLabel transferLabel;
    private javax.swing.JRadioButton virtualAccount;
    private javax.swing.JComboBox<String> virtualComboBox;
    private javax.swing.JLabel virtualLabel;
    // End of variables declaration//GEN-END:variables
}
